{% set name = "placekey" %}
{% set version = "0.0.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/placekey-{{ version }}.tar.gz
  sha256: ad5a3649d1bcddd2d67c726f1933b880c6d37e4289a051c6f284f249b46992d8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - backoff
    - h3-py
    - python >=3.6
    - ratelimit
    - requests
    - shapely

test:
  imports:
    - placekey
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Placekey/placekey-py
  summary: Utilities for working with Placekeys
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ecmascriptguru
